import React from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter, Link, NavLink, useLocation} from 'react-router-dom';
import './style.css';
import './register-sw.js';

const books=[
['Get More Customers','Attract the right people and turn attention into inquiries.'],
['Stop Losing Leads','Capture every inquiry and follow up consistently.'],
['Get Paid Faster','Make invoices and collections easier to manage.'],
['Keep Your Customers','Build trust, deliver well, and encourage repeat business.'],
['Get Your Time Back','Reduce repetitive admin and reclaim your workday.'],
['Run a Smarter Business','Make better decisions with clearer business information.']
];
const problems=['Not enough customers','Marketing ROI is unclear','Social media takes too much time','Quotes go cold','Customers do not return','Payments arrive late','Cash flow is hard to predict','Expenses keep rising','Profitability is unclear','Tax paperwork piles up','Inbox overload','Forgotten follow-ups','Repetitive paperwork','Owner is the bottleneck','Information is hard to find','Slow customer responses','Repeated FAQs','Lost commitments','Late projects','Bad reviews','Recruiting difficulties','Training gaps','Accountability','Inventory problems','Disconnected software','Poor visibility','No growth plan','Compliance uncertainty','Cybersecurity risks','Funding challenges'];
const niches=['Roofers','Landscapers','Salons','Accountants'];
const pathFor=(s)=>'/'+s;
function Shell({children}){const [open,setOpen]=React.useState(false);const location=useLocation();React.useEffect(()=>{setOpen(false);window.scrollTo(0,0)},[location.pathname]);return <><header className="header"><div className="container nav"><Link className="brand" to="/"><span className="bot">✳</span> Bot the Boring</Link><button className="menu" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(!open)}>☰</button><nav className={open?'links show':'links'} aria-label="Main navigation"><NavLink to="/books">Books</NavLink><NavLink to="/examples">Free examples</NavLink><NavLink to="/resources">DIY resources</NavLink><NavLink to="/automation">Automation</NavLink><NavLink to="/about">About</NavLink><Link className="btn small" to="/newsletter">Newsletter ↗</Link></nav></div></header><main>{children}</main><footer><div className="container foot"><div><Link className="brand" to="/">✳ Bot the Boring</Link><p>Less busywork. More customers. More time for what matters.</p></div><div className="footerlinks"><Link to="/newsletter">Newsletter</Link><Link to="/contact">Contact</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link></div></div><div className="container copyright">© {new Date().getFullYear()} Bot the Boring. Educational resources; results vary by business.</div></footer></>}
function Tag({children}){return <span className="eyebrow">{children}</span>}
function Heading({tag,title,desc}){return <div className="pagehead container"><Tag>{tag}</Tag><h1>{title}</h1>{desc&&<p className="lead">{desc}</p>}</div>}
function CTA(){return <section className="cta container"><div><Tag>One practical idea each week</Tag><h2>Bot the Boring Stuff.</h2><p>Less busywork. More customers. More time for what matters.</p></div><Link className="btn" to="/newsletter">Explore the newsletter →</Link></section>}
function Home(){return <><section className="hero container"><div><Tag>Small business, less busywork</Tag><h1>Do what you're <em>great at.</em><br/>Bot the boring.</h1><p className="lead">Practical ways to get more customers, stay on top of the work, and make AI useful—without becoming a tech expert.</p><div className="actions"><Link className="btn" to="/examples">Explore free examples →</Link><Link className="btn secondary" to="/newsletter">Get the newsletter</Link></div><p className="fine">Free resources. No login required.</p></div><div className="heroart" aria-label="Illustration of repetitive tasks becoming free time"><div className="note n1">Follow up with customers <span>✓</span></div><div className="note n2">Keep track of inquiries <span>✓</span></div><div className="note n3">Spend time on what matters <span>♥</span></div><div className="spark">✳</div></div></section><section className="section tint"><div className="container"><Tag>Simple by design</Tag><h2>Start with the problem.<br/>Not the technology.</h2><div className="steps">{['Do it yourself','Simplify it','Bot the boring','Get back to customers'].map((s,i)=><article className="step" key={s}><span className="number">0{i+1}</span><h3>{s}</h3><p>{['Learn a complete, practical method.','Remove unnecessary steps first.','Use AI where it actually helps, with human review.','Measure the difference and focus on your business.'][i]}</p></article>)}</div></div></section><section className="section container"><div className="sectiontop"><div><Tag>Free and useful</Tag><h2>See how it works<br/>in your kind of business.</h2></div><Link className="textlink" to="/examples">Explore examples →</Link></div><div className="cards four">{niches.map(n=><Link className="card niche" to={'/examples?niche='+n.toLowerCase()} key={n}><span className="nicheicon">{({Roofers:'⌂',Landscapers:'✿',Salons:'✂',Accountants:'▤'})[n]}</span><h3>{n}</h3><p>See a practical starting point.</p><span className="arrow">↗</span></Link>)}</div></section><section className="section container"><div className="sectiontop"><div><Tag>The book series</Tag><h2>Six books. Real problems.<br/>No magic buttons.</h2></div><Link className="textlink" to="/books">See all six →</Link></div><div className="cards three">{books.slice(0,3).map((b,i)=><article className="card book" key={b[0]}><div className={'cover cover'+i}><span>BOT THE BORING</span><strong>{b[0]}</strong><small>Practical small-business guide</small></div><h3>{b[0]}</h3><p>{b[1]}</p></article>)}</div></section><CTA/></>}
function Books(){return <><Heading tag="The Bot the Boring book series" title="A practical guide for every kind of busy." desc="Six planned books, each focused on a real small-business challenge. Learn the complete DIY method first; automation is always optional."/><section className="container section cards three">{books.map((b,i)=><article className="card book" key={b[0]}><div className={'cover cover'+i%3}><span>BOOK 0{i+1}</span><strong>{b[0]}</strong><small>Bot the Boring series</small></div><h2>{b[0]}</h2><p>{b[1]}</p><span className="fine">Planned title · publication date to be announced</span></article>)}</section><CTA/></>}
function Examples(){const q=new URLSearchParams(useLocation().search);const [niche,setNiche]=React.useState(q.get('niche')||'roofers');const [problem,setProblem]=React.useState('0');return <><Heading tag="Free niche examples" title="The same problem. Your kind of business." desc="Explore educational starting points. No account, purchase, or consultation required."/><section className="container section"><div className="selector"><label>Business type<select value={niche} onChange={e=>setNiche(e.target.value)}>{niches.map(n=><option key={n} value={n.toLowerCase()}>{n}</option>)}</select></label><label>Business problem<select value={problem} onChange={e=>setProblem(e.target.value)}>{problems.map((p,i)=><option key={p} value={i}>{p}</option>)}</select></label></div><div className="example"><Tag>Educational example · not a personalized plan</Tag><h2>{problems[Number(problem)]} — {niche}</h2><p>Start by writing down where this problem appears in your current workflow. Collect a small, representative sample before deciding whether a new tool is needed.</p><div className="steps mini"><article><h3>1. Do it yourself</h3><p>Record the current steps, owner, time spent, and outcome. Try a simple checklist or spreadsheet.</p></article><article><h3>2. Simplify it</h3><p>Remove repeated entry, unclear handoffs, and steps that add no customer value.</p></article><article><h3>3. Consider automation</h3><p>Only automate a repeatable, consent-appropriate step. Review AI output before it reaches customers.</p></article><article><h3>4. Measure</h3><p>Compare time, completion, and customer outcomes before and after your change.</p></article></div><p className="fine">This is a general framework, not a verified niche-specific case study. Detailed researched examples are in development.</p></div></section><CTA/></>}
function Resources(){return <><Heading tag="Free DIY resources" title="Useful before you buy anything." desc="A library of 30 common small-business problems. Choose one, then work through it step by step."/><section className="container section"><div className="problemgrid">{problems.map((p,i)=><Link className="problem" to={'/examples?problem='+i} key={p}><span>{String(i+1).padStart(2,'0')}</span>{p}<b>↗</b></Link>)}</div></section><CTA/></>}
function Newsletter(){return <><Heading tag="Bot the Boring Stuff" title="A little less busywork in your inbox." desc="One practical idea each week to help you find customers, simplify work, and use AI with confidence."/><section className="container section signup"><div className="panel"><h2>What you'll get</h2><div className="steps mini"><div><h3>One problem</h3><p>Something small-business owners actually face.</p></div><div><h3>One DIY fix</h3><p>A complete, useful action you can take yourself.</p></div><div><h3>One optional AI idea</h3><p>Only when it makes the work easier.</p></div></div></div><div className="panel pale"><Tag>Signup coming soon</Tag><h2>Be first to know.</h2><p>We're preparing a consent-based newsletter signup. The form is not active yet, and we're not collecting email addresses on this page.</p><div className="disabledform"><label htmlFor="email">Email address</label><input id="email" type="email" placeholder="you@yourbusiness.com" disabled/><button className="btn" disabled>Signup opens soon</button></div><p className="fine">No mailing list or subscription has been activated.</p></div></section></>}
function Automation(){return <><Heading tag="Optional software" title="Your business runs better. You stay in charge." desc="The DIY method is complete on its own. Optional automation may later help with repetitive work."/><section className="container section"><div className="cards three">{[['Capture','Organize incoming inquiries without losing context.'],['Follow up','Prepare drafts and reminders for human review.'],['Keep control','Consent, clear history, and the ability to stop.']].map(x=><article className="card" key={x[0]}><Tag>Planned capability</Tag><h2>{x[0]}</h2><p>{x[1]}</p></article>)}</div><p className="fine space">Software is not yet available. Any future pricing, integrations, and results will be verified before launch.</p></section><CTA/></>}
function About(){return <><Heading tag="Why we exist" title="Small businesses deserve their time back." desc="We believe the best technology gives owners more time for customers, craft, and the work they love."/><section className="container section prose"><h2>Useful, not complicated.</h2><p>Bot the Boring starts with ordinary business problems and practical solutions. We teach the do-it-yourself method first, simplify the work second, and consider AI only when it genuinely helps.</p><p>We don't promise that every task needs a bot—or that every business needs another subscription.</p></section><CTA/></>}
function Contact(){return <><Heading tag="Contact" title="Say hello." desc="Have a question, a suggestion, or a boring business problem worth covering?"/><section className="container section prose"><p>Our public contact channel is being configured. Please check back soon; we don't want to publish an unmonitored address.</p></section></>}
function Privacy(){return <><Heading tag="Privacy" title="Privacy matters."/><section className="container section prose"><p>This is a preliminary privacy notice, not a finalized legal policy. The newsletter signup is inactive and this site does not intentionally collect email addresses through a form.</p><p>Basic hosting and security systems may process technical request information. Before enabling subscriptions, we will publish details about data collected, processing purposes, providers, retention, unsubscribe rights, and contact information.</p><p>Do not submit personal information through inactive forms.</p></section></>}
function Terms(){return <><Heading tag="Terms" title="A few important details."/><section className="container section prose"><p>This is a preliminary notice pending legal review. Materials on this website are general educational information, not personalized legal, tax, financial, or professional advice.</p><p>Examples are illustrative, and business results vary. Planned books and software features are not promises of availability. No paid service is currently offered through this site.</p></section></>}
function App(){const loc=useLocation().pathname;const pages={'/':Home,'/books':Books,'/examples':Examples,'/resources':Resources,'/newsletter':Newsletter,'/automation':Automation,'/about':About,'/contact':Contact,'/privacy':Privacy,'/terms':Terms};const Page=pages[loc]||(()=> <Heading tag="404" title="This page wandered off." desc="Try the home page instead."/>);return <Shell><Page/></Shell>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
